version: '3.8'

services:
  game:
    build: .
    ports:
      - "8080:80"
    container_name: javascript-2d-game
    restart: unless-stopped
    # For development, you can uncomment the volume mount below
    # volumes:
    #   - .:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
